# Generated by Django 6.0.6 on 2026-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
