# Generated by Django 6.0.6 on 2026-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_project_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronologyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='chronology_images/')),
                ('video_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'date_label'],
            },
        ),
    ]
