# Generated by Django 6.0.6 on 2026-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_chronologyentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronologyentry',
            options={'ordering': ['date_label']},
        ),
        migrations.RemoveField(
            model_name='chronologyentry',
            name='order',
        ),
        migrations.AlterField(
            model_name='chronologyentry',
            name='date_label',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
