# Generated by Django 6.0.6 on 2026-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skill_logos/'),
        ),
    ]
