# Generated by Django 6.0.6 on 2026-07-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_skill_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
